title: SIAM-IMA Student Chapter Cardiff
description: Cardiff University Society for industrial and applied mathematics
show_downloads: true
google_analytics:
collections_dir: collections

sass:
  sass_dir: assets/css

collections:
  board_members:
    output: false
  talks:
    output: true
  events:
    output: true
